### ISSUE TITLE
Support multi-platform images

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#104]
#76 allows for configuring pulling/pushing for images from various platforms, but since it doesn't actually add support for [image indexes](https://github.com/opencontainers/image-spec/blob/main/image-index.md#image-index-property-descriptions), only a single platforms image can be represented in the store.

This change will involve adding support for image indexes for the `artifact.OCI` interface, and might not even be necessary since the user could create multiple stores for multiple architectures as long as they don't mix and match.

**Comment by zackbradys** [comment]
Possibly still applicable? @amartin120

**Comment by amartin120** [comment]
Supported with 0.4.x
