### ISSUE TITLE
Document API objects

### ISSUE THREAD

**Issue by nikkelma** [hauler-dev/hauler#111]
Fully document API objects available through hauler and their intended use.

- [ ] `contents` - `Files`
- [ ] `contents` - `Images`
- [ ] `contents` - `Charts`
- [ ] `collection` - `K3s`
- [ ] `collection` - `ThickCharts`
- [ ] `collection` - `ImageTxts`

**Comment by zackbradys** [comment]
Possibly still applicable? Depending on implementation of collections. @amartin120
