### ISSUE TITLE
Feature: Support a Terraform Provider and Modules Registry

### ISSUE THREAD

**Issue by flickerfly** [hauler-dev/hauler#117]
It'd be really helpful to provide tooling to build and deploy a Terraform provider and module registry alongside the rest of these things. This would mean that I can write my IaC to pick up the terraform providers and modules it needs from a central location more easily and not be hacking their details afresh each time throughout the code. 

For providers, I believe it would need to start with a [network mirror](https://www.terraform.io/cli/config/config-file#network_mirror)

For modules, We would need a [module registry](https://www.terraform.io/internals/module-registry-protocol).

It seems that both would just be a properly configured HTTP endpoint to host the information and then details on configuring terraform to point to this registry similar to the use of the container registry.

**Comment by zackbradys** [comment]
Worth while to explore and add to the extended roadmap. @amartin120

**Comment by flickerfly** [comment]
This seems exciting. Is there an associated PR or docs around somewhere?
