### ISSUE TITLE
Image Pulling: add line-delimited file parsing.

### ISSUE THREAD

**Issue by bgulla** [hauler-dev/hauler#118]
I would like to use hauler as a replacement to the docker runtime to pull rancher images. Rancher ships with `rancher-images.txt` which is a line delimited file containing all the images needed for rancher. 

Ideally, we could have hauler parse a file and pull all the images in succession.

`hauler store image --file ./rancher-images.txt`

**Comment by zackbradys** [comment]
Definitely still applicable. Possibly have Hauler parse any file for regex matching images, charts, or files? Would definitely need to be thought out considering the recent improvements. @amartin120

**Comment by zackbradys** [comment]
Bumping this issue! `Hauler` currently requires outside functionality (such as scripting) to achieve this functionality. Here is an example: https://github.com/zackbradys/rancher-airgap/blob/main/hauler/scripts/rancher/hauler-rancher.sh

**Comment by dweomer** [comment]
```bash
#!/usr/bin/env bash
set -ex -o pipefail

: "${VERSION:="v2.7.9"}"
declare -x ver="${VERSION#[vV]}"
declare -x dir="$(dirname $0)/v${ver}"
declare -x url="https://github.com/rancher/rancher/releases/download/v${ver}/rancher-images.txt"

mkdir -p "${dir}"

cat <<YAML > "${dir}/$(basename "${0%%.sh}").yaml"
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: carbide-rancher-images
  annotations:
    hauler.dev/version: "v${ver}"
spec:
  images:
$( (curl -fsSL "${url}" && echo) | uniq | sort | while read img; do test -z "${img}" || echo "  - name: \"rgcrprod.azurecr.us/${img/docker\.io/}\""; done)
YAML
```
