### ISSUE TITLE
[RFE] Hauler Store - Improve `hauler store info`

### ISSUE THREAD

**Issue by zackbradys** [hauler-dev/hauler#137]
**Is your feature request related to a problem? Please describe.**
* No

**Describe the solution you'd like**
* When users view the Hauler Store with `hauler store info`, it shows a list of the store contents such as files, images, charts, etc... When you have a very large store, with say 500+ items, it can be difficult to parse it. 
* I would suggest adding the ability to natively filter by adding a flag of `-t, --type` so users can more easily parse and navigate the contents of the store with `hauler store info -t image` or `hauler store info -t chart -o json`

**Describe alternatives you've considered**
* Parse the store with native linux tooling such a `hauler store info | grep chart`

**Additional context**
* Due to `hauler store info` needing to be improved, this could be an easy (maybe less of a lift) improvement!

**Comment by zackbradys** [comment]
Hey @amartin120, I noticed that PR https://github.com/rancherfederal/hauler/pull/146 seemed to address some of this issue, but curious if there is more work planned on `hauler store info`?

**Comment by amartin120** [comment]
I almost closed this issue but then I realized that you were looking for better filtering so I left it open until that's better addressed.  #146 addressed the fact that `hauler store info` was not able to accurately list image indexes and needed a complete overhaul.

**Comment by amartin120** [comment]
completed with https://github.com/rancherfederal/hauler/pull/150
