### ISSUE TITLE
[RFE] Encrypt store package for transit

### ISSUE THREAD

**Issue by Daemonslayer2048** [hauler-dev/hauler#154]
**Is your feature request related to a problem? Please describe.**
It is possible a hauler package could be intercepted in transit either via sneaker net, or some other means, it is also conceivable there could be proprietary information contained in said package. 

**Describe the solution you'd like**
Any sort of encryption of the store packages either via password, key, etc would improve the security of the package in transit. 

**Describe alternatives you've considered**
One alternative is to use a common application like openssl, the problem with this solution is now openssl needs to be included on the systems on the airgap side. It is also difficult to make assumptions about what packages will be available on the other side, so if this option was to be used, you would need to package openssl and bring that, hauler, and the hauler package. 

**Additional context**
N/A

**Comment by bgulla** [comment]
FWIW, most cross-domain scanners that I have used on customer networks strictly block and flag any encrypted binaries as they are not able to scan them for malware signatures (looking at you elasticsearch). While in theory I can see the applicability of the ask, the policy of our customer would negate the opportunity. 

Not closing this yet, but my view is that this could be accomplished by encrypting the `.tar.bst` file itself and decrypting on the destination network prior to handing to hauler.

**Comment by Daemonslayer2048** [comment]
I think your response is valid for systems that are networked. I am imagining a scenario though where the gapped network is not connected, so there is no pulling or pushing encrypted binaries across a network. 
For example: a user packages up their store, and enables some flag in hauler to encrypt the tarball, throw said tarball and hauler binary on a usb stick, walk it to said gapped cluster and install from there. In this scenario the tar ball is never pushed across a network and is still protected in transit to the final destination. 
One option would be to encrypt the USB stick, however we run into the issue again where now the final destination needs to be able to decrypt said USB.

**Comment by dweomer** [comment]
out of scope for core hauler
