### ISSUE TITLE
[BUG] Missing LICENSE declaration

### ISSUE THREAD

**Issue by dirkmueller** [hauler-dev/hauler#158]
**Environmental Info:**

Irrelevant

**Hauler Version:**
* 0.4.2

**Describe the bug:**
* 
The source distribution and git repository do not have a clear indication on what the license is. Please add a `LICENSE` or a `COPYING` file that declares the licensing of the hauler specific parts.

**Comment by amartin120** [comment]
Thanks for the reminder @dirkmueller.  We've added a license file. https://github.com/rancherfederal/hauler/pull/160
