### ISSUE TITLE
[RFE] Support export of images as tarballs 

### ISSUE THREAD

**Issue by starizard** [hauler-dev/hauler#174]
**Is your feature request related to a problem? Please describe.**
Need a way to load the images to all airgapped nodes, but don't want to run a registry,
Would be nice if the tool could spit out a tarball, that could be loaded with `docker load` or `ctr`

**Describe alternatives you've considered**
`docker save` and `docker load` with a loop

**Comment by dweomer** [comment]
this is a job for manifests, see: https://rancherfederal.github.io/hauler-docs/docs/guides-references/manifests
