### ISSUE TITLE
[RFE] store sync from URL

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#182]
**Is your feature request related to a problem? Please describe.**
Be able to use a stored manifest from an URL. 

**Describe the solution you'd like**
`hauler store sync -f https://raw.githubusercontent.com/clemenko/rke_airgap_install/main/air_gap_all_the_hauler.yaml`

**Describe alternatives you've considered**
copy file and then sync

**Additional context**
*

**Comment by clausa** [comment]
Alternatively, make the CarbideRegistry configurable (https://github.com/rancherfederal/hauler/blob/main/pkg/consts/consts.go#L53) to allow serving 'products' (basically air_gap_all_the_hauler.yaml) from an (OCI) registry:

```bash
hauler store sync --products <product>=<product-version> --product-registry=mycr.domain.tld 
```
where, --product-registry defaults to 'rgcrprod.azurecr.us'

Using a registry to serve 'air_gap_all_the_hauler.yaml' will also allow for signing and validation, etc. However, I do see the convenience of being able to just point Hauler to an URL. 

Please let me know, if you would prefer a separate RFE for making CarbideRegistry configurable.

**Comment by amartin120** [comment]
@clausa Thanks for this idea, and yes, please create a separate RFE for it if you don't mind.

**Comment by zackbradys** [comment]
Closing due to tracking this RFE via Issue https://github.com/rancherfederal/hauler/issues/208.
