### ISSUE TITLE
[BUG] improper exit code on failed command

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#185]
**Environmental Info:**
rocky 9

**Hauler Version:**
0.4.4

**System CPU architecture, OS, and Version:**
Linux iventoy 5.14.0-362.8.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 8 17:36:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug:**
when the hauler command failed it still has an exit code of "0" which tells bash it completed.

```bash
[root@iventoy hauler]# hauler store sync -f /opt/hauler/airgap_haulerdd.yaml
Error: open /opt/hauler/airgap_haulerdd.yaml: no such file or directory
Usage:
  hauler store sync [flags]

Flags:
  -f, --files strings      Path to content files
  -h, --help               help for sync
  -k, --key string         (Optional) Path to the key for signature verification
  -p, --platform string    (Optional) Specific platform to save. i.e. linux/amd64. Defaults to all if flag is omitted.
      --products strings   Used for RGS Carbide customers to supply a product and version and Hauler will retrieve the images. i.e. '--product rancher=v2.7.6'

Global Flags:
      --cache string       Location of where to store cache data (defaults to $XDG_CACHE_DIR/hauler)
  -l, --log-level string    (default "info")
  -s, --store string       Location to create store at (default "store")

1:47PM ERR open /opt/hauler/airgap_haulerdd.yaml: no such file or directory
[root@iventoy hauler]# echo $?
0
```

**Steps To Reproduce:**
type a filename wrong

` hauler store sync -f /opt/hauler/airgap_haulerdd.yaml `

**Expected behavior:**
when hauler has an `ERR` output an exit code of '1' is expected
`1:50PM ERR open /opt/hauler/airgap_haulerdd.yaml: no such file or directory`

**Actual behavior:**
exit code "0"

**Additional context / logs:**
I am trying to add error checking around the use of hauler and have correct exit codes is important.

**Comment by amartin120** [comment]
D'oh.  Easy fix.  I'll queue this up soon.  Thanks, @clemenko

**Comment by clemenko** [comment]
thanks @amartin120 fantastic!

**Comment by clemenko** [comment]
here is the use case : https://github.com/clemenko/rke_airgap_install/blob/main/hauler_all_the_things.sh#L149

**Comment by amartin120** [comment]
PR: https://github.com/rancherfederal/hauler/pull/187. (merged)

in line for v1.0.1, "soon"
