### ISSUE TITLE
[RFE] Change the "sync" output to be more informative

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#192]
**Is your feature request related to a problem? Please describe.**
Change the work "added" for "adding" when the file/image/chart is starting to be synced.
Then add " - ok" when done to let the user know that the file has been successfully synced.

This will help the user understand where in the process hauler is. This is important for `sync`ing large files.

**Describe the solution you'd like**
![hauler_info_idea](https://github.com/rancherfederal/hauler/assets/3177276/bda194e6-8bc6-44ae-9365-3d610853de07)

**Describe alternatives you've considered**
🤷 

**Additional context**
I LOVE HAULER!

**Comment by amartin120** [comment]
Not exactly as nice as you had in your example but hopefully better.  https://github.com/rancherfederal/hauler/pull/217

To be included in the next release.
