### ISSUE TITLE
[BUG] Store Add File name option not working

### ISSUE THREAD

**Issue by fgiudici** [hauler-dev/hauler#196]
**Environmental Info:**
*

**Hauler Version:**
* GitVersion:    1.0.0
* GitCommit:     79b240d

**Describe the bug:**
* the -n|--name option in the `hauler store add file -n desiredName filename.txt` is not working

**Steps To Reproduce:**
* hauler store add file -n desiredName filename.txt

**Expected behavior:**
* 

**Actual behavior:**
* 

**Additional context / logs:**
* looking at the code seems the actual implementation is missing

**Comment by amartin120** [comment]
Thank you!
