### ISSUE TITLE
[BUG] directories listed in manifests -path will cause files to build up in /tmp

### ISSUE THREAD

**Issue by aleiner** [hauler-dev/hauler#200]
**Environmental Info:**
* Rocky 8

**Hauler Version:**
* 1.0.0

**System CPU architecture, OS, and Version:**
* Linux adam-hauler 4.18.0-477.27.1.el8_8.x86_64 #1 SMP Wed Sep 20 15:55:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug:**
* If your manifest file contains a path that is a directory, hauler .gzip files will get created and left in /tmp.

**Steps To Reproduce:**
* Use manifest .yaml from #198 

**Expected behavior:**
* /tmp will get cleaned up

**Actual behavior:**
* /tmp does not get cleaned up

**Additional context / logs:**
*

**Comment by zackbradys** [comment]
Hey @aleiner, are you still having this issue? If so, are you able to reproduce it with one of the recent releases?

**Comment by aleiner** [comment]
We can close for now. I'll reopen if I run into this again.
