### ISSUE TITLE
[feature] Hauer serve registry readonly mode.

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#201]
**Is your feature request related to a problem? Please describe.**
`hauler store serve registry` is writable be default. Readonly should be the default. 

https://github.com/rancherfederal/hauler/blob/bb2a8bfbeca0f33998e0015e6f0cfeaa7ec3dc93/cmd/hauler/cli/store/serve.go#L139

**Describe the solution you'd like**
`hauler store serve registry` defaults to read only. Makes it more sane if you need to server out images locally. 

**Describe alternatives you've considered**
N/A

**Additional context**
Secure by default... :D

**Comment by zackbradys** [comment]
Closing as resolved per PR #277!
