### ISSUE TITLE
Support oci chart

### ISSUE THREAD

**Issue by koolay** [hauler-dev/hauler#204]
Hauler is not support to package oci chart.

**Comment by dweomer** [comment]
not intuitive but if you refer to the oci chart as an image instead of a chart this should suffice as a work-around. if this is not acceptable, please create a new issue and fill out one of "bug report" or "feature request" templates

**Comment by zackbradys** [comment]
Closing as resolved per PR https://github.com/rancherfederal/hauler/pull/245!
