### ISSUE TITLE
False error when performing a hauler store save

### ISSUE THREAD

**Issue by emichellecarter** [hauler-dev/hauler#206]
**Hauler Version:**

hauler: Airgap Swiss Army Knife

GitVersion:    1.0.1
GitCommit:     bb2a8bf
GitTreeState:  clean
BuildDate:     2024-02-27T16:30:03Z
GoVersion:     go1.21.7
Compiler:      gc
Platform:      linux/amd64

**Describe the Bug:**

When running a hauler store save command, the command returns a false error when the --filename and a --store flag is passed a false error is returned stating that the command does not accept any arguments.  However a hauler store list produces the correct results for the store created.
Error: accepts 0 arg(s), received 1
Usage:
  hauler store save [flags]

Flags:
  -f, --filename string   Name of archive (default "haul.tar.zst")
  -h, --help              help for save

Global Flags:
      --cache string       Location of where to store cache data (defaults to $XDG_CACHE_DIR/hauler)
  -l, --log-level string    (default "info")
  -s, --store string       Location to create store at (default "store")

5:45PM ERR accepts 0 arg(s), received 1

**Steps to Reproduce:**

```
hauler store save --filename $(System.DefaultWorkingDirectory)/${{ parameters.azureContainerRegistry }}.files.haul.tar.zst -s $(System.DefaultWorkingDirectory)/filestore
echo "List store info"
hauler store info -s $(System.DefaultWorkingDirectory)/filestore
```

**Expected Behavior:**

The command does not throw a false error in the pipeline.  Could potentially cause failures when automating the process.

-

**Actual Behavior:**

Produces false error as seen above but is added to the store as expected with the flags provided.

**Comment by dweomer** [comment]
i do not see this behavior:
![image](https://github.com/rancherfederal/hauler/assets/1033444/4a25c651-3773-45df-ae4e-b55d66addd93)

**Comment by dweomer** [comment]
tweaked your steps to reproduce for clarity. looks like you have a couple of different syntaxes in the mix. most likely cause is space(s) in your working directory. quote your flag values to avoid incorrect executions in your shell
