### ISSUE TITLE
[BUG] Hauler install script fails if sudo doesn't exist

### ISSUE THREAD

**Issue by bcdurden** [hauler-dev/hauler#233]
**Environmental Info:**

Docker
-

**Hauler Version:**

all
-

**Describe the Bug:**

Install script assumes sudo is installed and fails if it is not, even when running in the root context.
-

**Steps to Reproduce:**

Use this Dockerfile:
```
FROM ubuntu
RUN curl -sfL https://get.hauler.dev | bash
```

docker build -t test .

Watch failure:
```console
: RUN curl -sfL https://get.hauler.dev | bash
 ---> Running in c0b899c5851c

[ERROR] Hauler: sudo is not installed
Removing intermediate container c0b899c5851c
```
-

**Expected Behavior:**

Installs correctly without error.
-

**Actual Behavior:**

Fails to install.
-

**Comment by zackbradys** [comment]
duplicate issue to Issue https://github.com/rancherfederal/hauler/issues/253
