### ISSUE TITLE
[RFE] Create a "-debug" docker image with a shell

### ISSUE THREAD

**Issue by ethanchowell** [hauler-dev/hauler#251]
**Is this RFE related to an Existing Problem? If so, please describe:**

A pattern I've seen for a handful of things like kaniko and I think cosign as well is building an image `FROM scratch` but also producing another image with `-debug` appended to the tag with a shell. Since hauler only produces an image without a shell, current CI based workflows have to download hauler from the releases page.

**Describe Proposed Solution(s):**

Producing both a scratch image as well an image with a shell would allow users to run hauler in CI without having to download it every time. It would also enable patterns like  `FROM ghcr.io/rancherfederal/hauler:v1.0.3-debug` to do something like copy in a store as a tar.zst, load it and then set the entrypoint to something like `store serve registry`.

**Describe Possible Alternatives:**

I could just build my own image that does this, but it seems like an easy enough thing to work into the existing release pipelines that could benefit the user base.

**Additional Context:**

-

**Comment by dweomer** [comment]
Is this mooted by [`kubectl debug`](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_debug/)?

**Comment by zackbradys** [comment]
Closing as resolved per PR https://github.com/hauler-dev/hauler/pull/267!
