### ISSUE TITLE
[feature] remove sudo requirement within installscript

### ISSUE THREAD

**Issue by bcdurden** [hauler-dev/hauler#253]
**Is this RFE related to an Existing Problem? If so, please describe:**

- When installing harvester using the install script, the script attempts to call sudo without making a check (and handling) the case when it doesn't exist (even when superuser)

**Describe Proposed Solution(s):**

-The script should check for superuser first (UID 0). If not in the superuser context, check for the installation of sudo. If no sudo is detected, use the local user path bin directory instead with a warning label.

**Describe Possible Alternatives:**

-Remove the sudo command entirely from the script.

Current workaround:
`curl -sfL https://get.hauler.dev | sed 's/sudo//g' | HAULER_VERSION=1.0.3 bash`

**Comment by zackbradys** [comment]
Closing as resolved per PR https://github.com/hauler-dev/hauler/pull/280!
