### ISSUE TITLE
[feature] how to save a image to zst file by locally

### ISSUE THREAD

**Issue by Miaoxiang-philips** [hauler-dev/hauler#261]
Hi Team,

how to save a image to zst file by local?

i tried use `zstd -z test.tar` , then `hauler store load test.tar.zst`
but store folder is empty

<img width="529" alt="image" src="https://github.com/rancherfederal/hauler/assets/116536125/98c6bb9d-c329-4f96-8ea2-8a51f27497b7">

I know I could push to a Repository and then `hauler store add`, but that would be tedious, Is there a straightforward solution?

**Comment by KaminFay** [comment]
Hey! So if you're looking to save a haul to an archive you're going to want to use the save command mentioned here: [save docs](https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-save)

It should look like:
```
hauler store save -f test.tar.zst
```

**Comment by Miaoxiang-philips** [comment]
> Hey! So if you're looking to save a haul to an archive you're going to want to use the save command mentioned here: [save docs](https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-save)
> 
> It should look like:
> 
> ```
> hauler store save -f test.tar.zst
> ```

Thank you for your Reply
Let me clarify:

I know that you can save your local store image to a `zst` file via `hauler store save -f`, but when I have a tar file saved by `docker save -o test.tar`, I can't directly convert this tar file into a zst file that can be hauler loaded, I have to upload it to some registry and then `hauler add` it
then I can 'hauler store save'

But this is very cumbersome, is there a more suitable solution

**Comment by Miaoxiang-philips** [comment]
Hi @KaminFay , If anything is unclear, please ask me again

**Comment by zackbradys** [comment]
Hey @Miaoxiang-philips, right now you are not able to directly import `docker` compatible archives into `hauler`.

We've had a few users suggest this functionality and it's definitely on our radar, including the ability to export (save) as a `docker` compatible archive as well. We can keep this ticket open to reference and make sure to update it once we have more information and it's on the roadmap!

**Comment by zackbradys** [comment]
Closing as duplicated to Issue https://github.com/hauler-dev/hauler/issues/276. Expected in Hauler `v1.1.0`!
