### ISSUE TITLE
[BUG] Hauler trying enable ipv6.

### ISSUE THREAD

**Issue by clemenko** [hauler-dev/hauler#272]
**Environmental Info:**

Rocky 9.4

`Linux hauler 5.14.0-427.16.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 8 17:48:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

-

**Hauler Version:**

```
[root@hauler hauler]# hauler version
 __    __       ___       __    __   __       _______ .______
|  |  |  |     /   \     |  |  |  | |  |     |   ____||   _  \
|  |__|  |    /  ^  \    |  |  |  | |  |     |  |__   |  |_)  |
|   __   |   /  /_\  \   |  |  |  | |  |     |   __|  |      /
|  |  |  |  /  _____  \  |  `--'  | |  `----.|  |____ |  |\  \----.
|__|  |__| /__/     \__\  \______/  |_______||_______|| _| `._____|
hauler: Airgap Swiss Army Knife

GitVersion:    1.0.4
GitCommit:     05e67bc
GitTreeState:  clean
BuildDate:     2024-06-26T03:29:02Z
GoVersion:     go1.21.11
Compiler:      gc
Platform:      linux/amd64
```

-

**Describe the Bug:**

Hauler is logging to `/var/log/messages` the following:
```
Jul 25 00:30:59 hauler NetworkManager[788]: <warn>  [1721867459.5648] platform-linux: do-add-ip6-address[2: fe80::9436:bff:fedc:3d43]: failure 13 (Permission denied - ipv6: IPv6 is disabled on this device)
Jul 25 00:30:59 hauler NetworkManager[788]: <warn>  [1721867459.5648] l3cfg[a49669bcae08eef3,ifindex=2]: unable to configure IPv6 route: type unicast fe80::/64 dev 2 metric 1024 mss 0 rt-src ipv6ll
Jul 25 00:31:01 hauler NetworkManager[788]: <warn>  [1721867461.5670] ipv6ll[4b1e69a26f5728db,ifindex=2]: changed: no IPv6 link local address to retry after Duplicate Address Detection failures (back off)
```

-

**Steps to Reproduce:**

disable ipv6 on a rocky/rhel node and install hauler. Then run `hauler store serve fileserver` and `hauler store serve registry`

-

**Expected Behavior:**

NOT logging for ipv6.

-

**Actual Behavior:**

See errors above. 

-

**Additional Context:**

-

**Comment by dweomer** [comment]
how is ipv6 being disabled? (looks like the kernel module is loaded).
if ipv6 isn't disabled for every network interface i expect that you would see these kinds of logs for every nic that is seen by the systemd service when binding to 0.0.0.0

**Comment by clemenko** [comment]
I disabled it with `sysctl -w net.ipv6.conf.all.disable_ipv6=1`.

**Comment by dweomer** [comment]
@clemenko are you using the systemd unit proposed at https://github.com/hauler-dev/hauler/pull/181/files or something slightly different? please add the unit file that your are using as a comment or edit your bug report to include it as additional context.

---

err, well, i guess this an assumption on my part. if however you are straight up running `hauler store serve ...` then nevermind!

**Comment by clemenko** [comment]
Here is the systemd file 
```
# /etc/systemd/system/hauler.service
[Unit]
Description=Hauler Serve %I Service

[Service]
Environment="HOME=/opt/hauler/"
ExecStart=/usr/local/bin/hauler store serve %i -s /opt/hauler/store
WorkingDirectory=/opt/hauler

[Install]
WantedBy=multi-user.target
```

basically hauler is assuming ipv6 is there and it is not.

**Comment by zackbradys** [comment]
Hey @clemenko, are you able to start with a fresh node of `rocky`/`rhel` and test this again and paste the output and commands ran on the node?

**Comment by clemenko** [comment]
this appears to not be a hauler issue. sorry for the confusion.
