### ISSUE TITLE
[feature] TLS Support for Serve

### ISSUE THREAD

**Issue by wcrum** [hauler-dev/hauler#273]
**Is this RFE related to an Existing Problem? If so, please describe:**

- No open issue is related to this existing problem. When utilizing Hauler in some controlled environments, HTTP is restricted due to certificate or security reasons.

**Describe Proposed Solution(s):**

- Within `hauler store serve fileserver` support `--tls-cert` and `--tls-key` to support hauler server running HTTPS.

**Describe Possible Alternatives:**

- [hauler-dev/hauler-helm](https://github.com/hauler-dev/hauler-helm) has reference to support TLS via Secrets, although this suffices within a K8s environment, as a administrator bootstrapping environments I want to be able to utilize HTTPS prior to Hauler deployment.

**Additional Context:**

- Some Navy environments have ACLs to prevent internal usage of HTTP/80.
- Fintech, health and defense organizations commonly explicitly deny HTTP.
- `hauler store serve registry -c` supports configuration of TLS.

**Comment by wcrum** [comment]
Happy to work on this enhancement if this is something you all, the maintainers believe would be valuable. Let me know.

**Comment by zackbradys** [comment]
Hey @wcrum! Thanks for submitting this issue and feature request (RFE). 

We have always had password and certificates on our mind for `hauler store serve registry` and `hauler store serve fileserver`, but haven't implemented it yet (obviously). If you're able to take a stab at implementing it, it would be appreciated! If not, no worries and we will try to get this as soon as possible!

**Comment by wcrum** [comment]
Working on it!
