### ISSUE TITLE
[BUG] writing file: invalid input: reserved block type encountered

### ISSUE THREAD

**Issue by erpz22** [hauler-dev/hauler#292]
We are using EIB 1.0.2 and here are details for the environment.

**Environmental Info:**

- `Linux test-000c297d8057-62054 5.14.21-150500.55.19-default #1 SMP PREEMPT_DYNAMIC Tue Aug 8 22:15:01 UTC 2023 (9908c29) x86_64 x86_64 x86_64 GNU/Linux`

**Hauler Version:**

-   
 ```
  __       ___       __    __   __       _______ .______
|  |  |  |     /   \     |  |  |  | |  |     |   ____||   _  \
|  |__|  |    /  ^  \    |  |  |  | |  |     |  |__   |  |_)  |
|   __   |   /  /_\  \   |  |  |  | |  |     |   __|  |      /
|  |  |  |  /  _____  \  |  `--'  | |  `----.|  |____ |  |\  \----.
|__|  |__| /__/     \__\  \______/  |_______||_______|| _| `._____|
hauler: Airgap Swiss Army Knife

GitVersion:    devel
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.21.10
Compiler:      gc
Platform:      linux/amd64
```

**Describe the Bug:**

- ./hauler store load -l debug <xyz-file>-registry.tar.zst

**Steps to Reproduce:**

- Sorry we can not provide the images for some reason.

**Expected Behavior:**

- hauler store load successfully.

**Actual Behavior:**

- Use hauler as an embedded registry in SUSE Edge 3.0 with EIB, one of our image is pretty large (>12GB), the EIB use  build with hauler tar.zst file successfully, but when we use ISO to install on testing, the hauler failed to load the tar.zst files and popup error messages:

Error: reading file in tar archive: /tmp/hauler1333876749/blobs/sha256/e0fd1eb76533063439443407262f4481b8fdd9089a88c714d3e24eede193cbec: writing file: invalid input: reserved block type encountered

**Additional Context:**

-

**Comment by erpz22** [comment]
Try to decompressed the zst file using zstd commands, it works well on Ubuntu 23.10 zstd commands but encountered problems on SUSE micro linux zstd versions on 1.5.0 & 1.5.6, here is the error message:
`Decoding error (36) : Data corruption detected`

**Comment by zackbradys** [comment]
Hey @erpz22! Thanks for submitting an issue. 

Could you try using the latest version of Hauler (`v1.0.7`) and see if you are running into the same issue and error? We had some edge case issues with `v1.0.5`/`v1.0.6`.

**Comment by erpz22** [comment]
> Hey @erpz22! Thanks for submitting an issue.
> 
> Could you try using the latest version of Hauler (`v1.0.7`) and see if you are running into the same issue and error? We had some edge case issues with `v1.0.5`/`v1.0.6`.

Hi @zackbradys  Thanks for your reply, we digged into the problem and find it may be caused by other issues.
I will close this one and move it to EIB project.

https://github.com/suse-edge/edge-image-builder/issues/531

**Comment by erpz22** [comment]
> Hey @erpz22! Thanks for submitting an issue.
> 
> Could you try using the latest version of Hauler (`v1.0.7`) and see if you are running into the same issue and error? We had some edge case issues with `v1.0.5`/`v1.0.6`.

It works after replace to the newest hauler version, but that have to rebuild EIB images to replace the rpm installed one in EIB v1.0.2 will you provide the upgrade for all release EIB versions?
