### ISSUE TITLE
[BUG] `bash` complete issues

### ISSUE THREAD

**Issue by a1994sc** [hauler-dev/hauler#301]
**Environmental Info:**

- `Linux hostname 6.10.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 14 15:49:44 UTC 2024 x86_64 GNU/Linux`

**Hauler Version:**

- `1.0.7`

**Describe the Bug:**

- The shell auto-complete seems to be broken, it generates auto-complete for the program `bash` / `zsh` / `fish`, not `hauler`

**Steps to Reproduce:**

1. `docker pull ghcr.io/hauler-dev/hauler:v1.0.7`
2. `docker run ghcr.io/hauler-dev/hauler:v1.0.7 completion bash`

**Expected Behavior:**

- It should have an output like the following at the bottom

```text
if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_hauler hauler
else
    complete -o default -o nospace -F __start_hauler hauler
fi
```

**Actual Behavior:**

- It has the following

```text
if [[ $(type -t compopt) = "builtin" ]]; then
    complete -o default -F __start_bash bash
else
    complete -o default -o nospace -F __start_bash bash
fi
```

**Additional Context:**

I was able to make things work but applying the following patch

```text
diff --git a/cmd/hauler/cli/completion.go b/cmd/hauler/cli/completion.go
index e42bf20..8d50263 100644
--- a/cmd/hauler/cli/completion.go
+++ b/cmd/hauler/cli/completion.go
@@ -9,7 +9,7 @@ import (

 func addCompletion(parent *cobra.Command) {
 	cmd := &cobra.Command{
-		Use:   "completion",
+		Use:   "hauler completion",
 		Short: "Generates completion scripts for various shells",
 		Long:  `The completion sub-command generates completion scripts for various shells.`,
 	}
```

I will submit a PR later today with that change.

**Comment by zackbradys** [comment]
Hey @a1994sc, thanks for submitting the issue and catching this. Looking forward to taking a look at the PR!

**Comment by a1994sc** [comment]
@zackbradys Submitted a PR!
