### ISSUE TITLE
[BUG] Adding a local chart not working

### ISSUE THREAD

**Issue by Morgimiel** [hauler-dev/hauler#314]
**Environmental Info:**

MINGW64

-

**Hauler Version:**

1.0.7

-

**Describe the Bug:**

Running the following command doesn't work:
`hauler store add chart ./mychart-0.1.0.tgz`

Returns the following error `ERR repo  not found`

-

**Steps to Reproduce:**

Run the commands above

-

**Expected Behavior:**

I expect hauler to load local chart

-

**Actual Behavior:**

Hauler seems to search for a --repo flag even if I load local chart, as of described in the documentation.

-

**Additional Context:**

:3

-

**Comment by Morgimiel** [comment]
It looks like it can work, but I was missing the `--repo .` flag. It's missing from the documentation though. I think it should be optionnal

**Comment by zackbradys** [comment]
Hey @Morgimiel, when we added functionality to pull OCI Helm Charts, the command changed to requiring `--repo` and the documentation never got updated in the CLI and online docs. I’m working on an update and already including this in the changes.
