### ISSUE TITLE
Add better docs to README focusing on experience on connected vs disconnected systems

### ISSUE THREAD

**Issue by bgulla** [hauler-dev/hauler#33]
Please document the user experience better on the README. I would ideally like to see the example walk through the scenario of a) grabbing all the dependencies and b) then deploying those dependencies as a cluster. I don't think we do a great job of showing the value of hauler in the current docs form.

**Comment by zackbradys** [comment]
Closing as resolved due to https://github.com/rancherfederal/hauler-docs
