### ISSUE TITLE
[nit] make consts.CarbideRegistry a var so that it can be overridden at build time

### ISSUE THREAD

**Issue by dweomer** [hauler-dev/hauler#365]
https://github.com/hauler-dev/hauler/pull/354#discussion_r1842736807:
![image](https://github.com/user-attachments/assets/2216583e-b57d-4a96-9d8a-0bd8ebcdb12e)

**Comment by dweomer** [comment]
probably a bad idea 🤔

**Comment by zackbradys** [comment]
hey @dweomer, I would agree that this is probably no needed. feel free to reopen if you want to revisit...
