### ISSUE TITLE
[BUG] hauler registry doesn't accept images pushed by crane

### ISSUE THREAD

**Issue by valentin-nasta** [hauler-dev/hauler#375]
**Environmental Info:**

-

**Hauler Version:**

1.1.0
-

**Describe the Bug:**

crane push or a docker image saved as tar fails

```
crane push --verbose --insecure testdata/hello-world-amd64.tar localhost:5000/hello-world:latest

2024/12/05 15:34:08 --> POST http://localhost:5000/v2/hello-world/blobs/uploads/
2024/12/05 15:34:08 HTTP/1.1 405 Method Not Allowed
Content-Length: 19
Allow: GET, HEAD
Content-Type: text/plain; charset=utf-8
Date: Thu, 05 Dec 2024 15:34:08 GMT
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff

Method not allowed
```
-

**Steps to Reproduce:**

https://github.com/hauler-dev/hauler/compare/main...valentin-nasta:hauler:crane-upload-test
-
I mainly saved the hello-world docker image and tried it to push it with crane
```
docker pull --platform linux/amd64 hello-world
docker save hello-world -o testdata/hello-world-amd64.tar
crane push --verbose --insecure testdata/hello-world-amd64.tar localhost:5000/hello-world:latest


::1 - - [05/Dec/2024:15:22:04 +0000] "HEAD /v2/hello-world/manifests/latest HTTP/1.1" 404 96 "" "crane/0.20.2 go-containerregistry/0.20.2"
time="2024-12-05T15:22:04.471055244Z" level=error msg="response completed with error" err.code="blob unknown" err.detail="sha256:d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a" err.message="blob unknown to registry" go.version="go1.23.4 X:boringcrypto" http.request.host="localhost:5000" http.request.id=51976079-ee52-4937-a6e1-e52b359ad8db http.request.method=HEAD http.request.remoteaddr="[::1]:60256" http.request.uri="/v2/hello-world/blobs/sha256:d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a" http.request.useragent="crane/0.20.2 go-containerregistry/0.20.2" http.response.contenttype=application/json http.response.duration="125.003µs" http.response.status=404 http.response.written=157 vars.digest="sha256:d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a" vars.name=hello-world version=v3.0.0+unknown
::1 - - [05/Dec/2024:15:22:04 +0000] "HEAD /v2/hello-world/blobs/sha256:d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a HTTP/1.1" 404 157 "" "crane/0.20.2 go-containerregistry/0.20.2"
::1 - - [05/Dec/2024:15:22:04 +0000] "POST /v2/hello-world/blobs/uploads/ HTTP/1.1" 405 19 "" "crane/0.20.2 go-containerregistry/0.20.2"
Error: POST http://localhost:5000/v2/hello-world/blobs/uploads/: unexpected status code 405 Method Not Allowed: Method not allowed
```

**Expected Behavior:**

image should be pushed to registry
-

**Actual Behavior:**
if fails with 405 method not allowed

-

**Additional Context:**

complete test case is on this commit:
https://github.com/hauler-dev/hauler/commit/e4958f3267df43d8826cdef4a32240410509aef8

-
Additional info:
I saw that with hauler version 1.0.4 crane push is working, but not with the versions starting with 1.0.5-rc.1 
couldn't pin point the exact commit yet.

https://github.com/hauler-dev/hauler/compare/v1.0.4...v1.0.5-rc.1

**Comment by zackbradys** [comment]
hey @valentin-nasta... we introduced new behavior to the `registry` in `v1.0.5` that defaults the `registry` to be `readonly`. You can opt into allow writes to the registry with the `--readonly=false` flag, but we don't support updates to a `store` when manually writing to the `registry` or `fileserver`...

`Hauler` has a source of truth known as the `store` and I don't see us supporting manual updates to `registry` or `fileserver` right now... but let us know if you have a good use case and we can consider it!
