### ISSUE TITLE
Add capability for user defined collections

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#46]
Introduce the concepts of `Collections` to allow for user defined sets of known hauler `content`. 

`collections` should allow for users to define their own api, and their own `driver` logic.  `drivers` are user defined images that contain the business logic of how to fetch content.  hauler will be responsible for running these images, and providing the inputs (sources) and processing the outputs (sinks).

Hauler should provide the source to the `driver` and expect a sink based on the following criteria:

**driver contract:**

source:
* the users `collection` as a string to stdin

sink:
* optional: an oci layout in a location specified by `hauler`
* optional: an `output.yaml` containing known hauler `content`

**Comment by zackbradys** [comment]
Possibly still applicable? Related to #52, #53, and #81. @amartin120
