### ISSUE TITLE
Ensure content store's can be entirely declarative

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#58]
Hauler can currently `sync` various types of declarative `Content`, but there isn't a guarantee that a `store` is entirely defined by a set of `Contents`.  In other words, the `store.Add()` that `sync` uses is imperative, and is missing something like `store.Remove()`.

**Comment by zackbradys** [comment]
Possibly still relevant? Part of the redesign of the store? @amartin120

**Comment by dweomer** [comment]
closing in favor of #202
