### ISSUE TITLE
support multi platform images

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#64]
current behavior defaults to the images default platform (defined in the image manifest). 

Desired enhancements include:
* allow for user defined `Platform`
* add configuration option to use all images

**Comment by joshrwolf** [comment]
related/duplicate of #76

**Comment by nikkelma** [comment]
Issues #76 and #104, when combined, cover this issue. Preferring two well-defined issues instead of one blanket issue; closing as a result.
