### ISSUE TITLE
Ensure `Platform` is configurable for `content`

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#76]
hauler currently defaults to the contents default platform defined in the manifest index.  This works _sometimes_, but making it user configurable would be ideal.

**Comment by nikkelma** [comment]
Would an operation mode of "bundle + serve all architectures" be an option included in this feature?

**Comment by joshrwolf** [comment]
it's an option but it would require some changes to `artifact.OCI` which currently only expects a single manifest/config/layers, that would have to shift to an index.  

imo the easier option (for now at least) is to allow a singularly configurable platform input

**Comment by amartin120** [comment]
resolving with https://github.com/rancherfederal/hauler/pull/164
