### ISSUE TITLE
better docs explaining hauler's purpose and usecases

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#77]
The current docs don't really do much outside of teach you some basic commands, and the README is lackluster.

Items below are some areas to address

- [ ] more descriptive top level README
- [ ] asciinema in top level README walking through basic hauler happy paths
- [ ] detailed walkthrough for e2e usecase (fetch contents, install k3s, install stuff on k3s?)

**Comment by joshrwolf** [comment]
whizz bang demo

1. use hauler to fetch k3s dependencies
2. use hauler to fetch some chart dependencies (cert-manager/grafana/hello-world, something with a UI preferrably)
3. hauler store save
4. -- transport to airgap --
5. use hauler to serve things
6. spin up k3s pointing to hauler's registry
7. spin up app brought in (2)

**Comment by nikkelma** [comment]
Demos should cover all `contents` use cases as well as an example `collection` use case; for the Rancher-focused target audience, installing k3s/RKE2 + Helm + cert-manager + Rancher is a great user story to have an example around.

**Comment by zackbradys** [comment]
Closing as resolved. https://github.com/rancherfederal/hauler-docs
