### ISSUE TITLE
ensure `hauler` can serve `hauler`

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#79]
to address the pain points of having to rsync/scp hauler around in an airgap environment to every location hauler is required, ensure hauler can collect and serve itself through a `curl`able  endpoint

**Comment by joshrwolf** [comment]
potentially just add an optional arg that adds the right hauler platform/arch during `save` time instead of `sync` time.

something like:

```
hauler store save --embed
# -- airgap --

hauler store serve

# $highport is some random unauthenticated high port not part of the registry
curl $haulerurl:$highport -o hauler
```

**Comment by zackbradys** [comment]
Definitely still applicable! Should be addressed in one of short milestones. @amartin120

**Comment by dweomer** [comment]
work-around:
- create a hauler manifest that references the desired version of hauler
- ⬇️ `hauler store sync --files hauler.yaml`
- ⬆️ `hauler store load [...]`
- ⬆️ `hauler store serve fileserver`
see:
- https://rancherfederal.github.io/hauler-docs/docs/guides-references/manifests
- https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-fileserver
