### ISSUE TITLE
add `rke2` collection

### ISSUE THREAD

**Issue by joshrwolf** [hauler-dev/hauler#81]

**Comment by zackbradys** [comment]
Possibly still applicable with #46, #52, and #53? @amartin120

**Comment by dweomer** [comment]
satisfied by invoking `hauler store sync --products rke2=v1.29.2+rke2r1`, see:
- https://rancherfederal.github.io/hauler-docs/docs/guides-references/carbide-customers
- https://rancherfederal.github.io/carbide-docs/docs/registry-docs/copying-images#rke2
