### ISSUE TITLE
Potential Bug: Can't download from authenticated registry

### ISSUE THREAD

**Issue by neoakris** [hauler-dev/hauler#94]
**Environmental Info:**          
RHEL7 x64, bash

**Hauler Version:**         
`hauler version`
```
GitVersion:  0.2.1
GitCommit:   32d24b2
BuildDate:   2021-11-16T19:05:25Z
GoVersion:   go1.17.3
Compiler:    gc
Platform:    linux/amd64
```

**System CPU architecture, OS, and Version:**
`uname -a`     
```
Linux master 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug:**
Can't seem to pull from authenticated repo using the declarative contents file

**Steps To Reproduce:**
```
curl -L https://github.com/rancherfederal/hauler/releases/download/v0.2.1/hauler_0.2.1_linux_amd64.tar.gz > hauler.tar.gz
tar -xzf hauler.tar.gz
sudo mv hauler /usr/bin/hauler

export REGISTRY1_USERNAME=<REPLACE_ME>
export REGISTRY1_PASSWORD=<REPLACE_ME>
echo $REGISTRY1_PASSWORD | docker login registry1.dso.mil --username $REGISTRY1_USERNAME --password-stdin

docker pull registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:1.7.1
# works

cat > debug-hauler-config.yaml <<EOF
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: bigbang-images
spec:
  images:
    - ref: registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:1.7.1
EOF

hauler store sync -f debug-hauler-config.yaml
# Error: GET https://registry1.dso.mil/v2/ironbank/elastic/eck-operator/eck-operator/manifests/1.7.1: UNAUTHORIZED: unauthorized to access repository: ironbank/elastic/eck-operator/eck-operator, action: pull: unauthorized to access repository: ironbank/elastic/eck-operator/eck-operator, action: pull
# Usage:
#   hauler store add image [flags]
# 
# Flags:
#   -h, --help   help for image
# 
# Global Flags:
#       --cache string       Location of where to store cache data (defaults to $XDG_CACHE_DIR/hauler)
#   -l, --log-level string    (default "info")
#   -s, --store string       Location to create store at (defaults to $PWD/store)
# 
# 4:12AM ERR GET https://registry1.dso.mil/v2/ironbank/elastic/eck-operator/eck-operator/manifests/1.7.1: UNAUTHORIZED: unauthorized to access repository: ironbank/elastic/eck-operator/eck-operator, action: pull: unauthorized to access repository: ironbank/elastic/eck-operator/eck-operator, action: pull
```

**Expected behavior:**         
* Since docker pull works I expect hauler store to work
* Note the following imperative hauler command gives the same error        
`hauler store add image registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:1.7.1`
* Side note the time is off as well, system time says 11:11pm, hauler shows 4:11am

**Actual behavior:**
Error seen above

**Additional context / logs:**
* @joshrwolf will be better able to debug as he has access to registry1.dso.mil  
* That being said registry1.dso.mil allows open self registration

**Comment by neoakris** [comment]
ah this is a duplicate issue https://github.com/rancherfederal/hauler/issues/35

**Comment by joshrwolf** [comment]
this should be fixed in master with #87, and will be released with #93.

the default behavior will now use the same creds that docker uses, so `docker login ...` first, and then subsequent `hauler` commands will leverage the same keychain, but each command that interacts with a remote registry will also allow for a `--username` and `--password` entry.

**Comment by joshrwolf** [comment]
will leave this open until #93 is closed and let you validate that it functions as you'd expect

**Comment by zackbradys** [comment]
Closing as resolved.

**Comment by zackbradys** [comment]
Closing as resolved.
